//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Script/ControladorBarco.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControladorBarco : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControladorBarco()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControladorBarco"",
    ""maps"": [
        {
            ""name"": ""Barco"",
            ""id"": ""6f608a25-6d40-4c2c-aca8-ed70c7e4a660"",
            ""actions"": [
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""51c7c6f7-93af-4ff3-8ce8-8400af00f7c3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6db2c7e3-e53f-4fdc-9f3c-a5e8cdb4717a"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""115c554e-ab01-4657-b4d8-c069e9c3ab95"",
                    ""path"": ""<XInputController>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c481ba50-7f3f-4335-96ce-45637a0a4eb3"",
                    ""path"": ""<DualShockGamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Barco
        m_Barco = asset.FindActionMap("Barco", throwIfNotFound: true);
        m_Barco_Look = m_Barco.FindAction("Look", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Barco
    private readonly InputActionMap m_Barco;
    private IBarcoActions m_BarcoActionsCallbackInterface;
    private readonly InputAction m_Barco_Look;
    public struct BarcoActions
    {
        private @ControladorBarco m_Wrapper;
        public BarcoActions(@ControladorBarco wrapper) { m_Wrapper = wrapper; }
        public InputAction @Look => m_Wrapper.m_Barco_Look;
        public InputActionMap Get() { return m_Wrapper.m_Barco; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BarcoActions set) { return set.Get(); }
        public void SetCallbacks(IBarcoActions instance)
        {
            if (m_Wrapper.m_BarcoActionsCallbackInterface != null)
            {
                @Look.started -= m_Wrapper.m_BarcoActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_BarcoActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_BarcoActionsCallbackInterface.OnLook;
            }
            m_Wrapper.m_BarcoActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
            }
        }
    }
    public BarcoActions @Barco => new BarcoActions(this);
    public interface IBarcoActions
    {
        void OnLook(InputAction.CallbackContext context);
    }
}
